import { useEffect, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { ArrowRight, BriefcaseBusiness, Plus, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { createInvestorDeal, listInvestorDeals, type DealRoom } from "@/lib/api/investorDeals";

export function DealPipeline() {
  const [deals, setDeals] = useState<DealRoom[]>([]); const [params] = useSearchParams(); const [loading, setLoading] = useState(true); const projectId = params.get("projectId");
  useEffect(() => { listInvestorDeals().then((result) => setDeals(result.deals)).catch(() => toast.error("Unable to load deal rooms.")).finally(() => setLoading(false)); }, []);
  const create = async () => { if (!projectId) return toast.error("Open a startup from Deal Intelligence to start a Deal Room."); try { const result = await createInvestorDeal(projectId); setDeals((current) => [result.deal, ...current]); toast.success("Deal Room created. NDA signature is required before diligence access."); } catch { toast.error("Unable to create the Deal Room for this relationship."); } };
  return <div className="min-h-full bg-[#0a0a0a] p-6 text-gray-100 lg:p-8"><div className="mx-auto max-w-6xl space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-bold text-white">Investor Deal Pipeline</h1><p className="mt-1 text-gray-400">Permissioned diligence rooms connected to your existing investor relationships.</p></div><button onClick={create} className="inline-flex items-center gap-2 rounded-lg bg-[#20C997] hover:bg-[#1ba87e] px-4 py-2 text-sm font-semibold text-black transition-colors"><Plus className="h-4 w-4" />Create Deal Room</button></div>{projectId && <div className="rounded-lg border border-[#20C997]/20 bg-[#20C997]/5 p-4 text-sm text-[#20C997]">Selected startup relationship: <span className="font-mono">{projectId}</span></div>}{loading ? <div className="rounded-lg border border-gray-800 bg-[#111111] p-8 text-center text-gray-400">Loading deal rooms...</div> : deals.length === 0 ? <div className="rounded-lg border border-gray-800 bg-[#111111] p-10 text-center"><BriefcaseBusiness className="mx-auto mb-3 h-8 w-8 text-gray-500" /><p className="text-gray-300">No active Deal Rooms yet.</p><p className="mt-1 text-sm text-gray-500">Request an introduction from a startup profile, then open a permissioned diligence room.</p></div> : <div className="grid gap-4 md:grid-cols-2">{deals.map((deal) => <Link key={deal.id} to={`/investor/deals/${deal.id}`} className="rounded-lg border border-gray-800 bg-[#111111] p-5 transition hover:border-[#20C997]/40"><div className="flex items-start justify-between"><div><p className="font-semibold text-white">Project {deal.projectId}</p><p className="mt-1 font-mono text-xs text-gray-500">{deal.id}</p></div><span className="rounded-full border border-[#20C997]/30 bg-[#20C997]/10 px-2 py-1 text-xs text-[#20C997] font-medium">{deal.state}</span></div><div className="mt-5 flex items-center justify-between text-sm"><span className={deal.ndaSigned ? "text-[#20C997]" : "text-amber-300"}><ShieldCheck className="mr-1 inline h-4 w-4" />{deal.ndaSigned ? "NDA signed" : "NDA required"}</span><span className="text-gray-400">{deal.diligence.completed}/{deal.diligence.total} complete <ArrowRight className="ml-1 inline h-4 w-4" /></span></div></Link>)}</div>}</div></div>;
}
