import { useEffect, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { ArrowRight, BriefcaseBusiness, Plus, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { createInvestorDeal, listInvestorDeals, type DealRoom } from "@/lib/api/investorDeals";

export function DealPipeline() {
  const [deals, setDeals] = useState<DealRoom[]>([]); const [params] = useSearchParams(); const [loading, setLoading] = useState(true); const projectId = params.get("projectId");
  useEffect(() => { listInvestorDeals().then((result) => setDeals(result.deals)).catch(() => toast.error("Unable to load deal rooms.")).finally(() => setLoading(false)); }, []);
  const create = async () => { if (!projectId) return toast.error("Open a startup from Deal Intelligence to start a Deal Room."); try { const result = await createInvestorDeal(projectId); setDeals((current) => [result.deal, ...current]); toast.success("Deal Room created. NDA signature is required before diligence access."); } catch { toast.error("Unable to create the Deal Room for this relationship."); } };
  return <div className="min-h-full bg-background-inverse p-6 text-text-on-inverse lg:p-8"><div className="mx-auto max-w-6xl space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-bold text-white">Investor Deal Pipeline</h1><p className="mt-1 text-text-on-inverse-muted">Permissioned diligence rooms connected to your existing investor relationships.</p></div><button onClick={create} className="inline-flex items-center gap-2 rounded-lg bg-status-success px-4 py-2 text-sm font-semibold text-black"><Plus className="h-4 w-4" />Create Deal Room</button></div>{projectId && <div className="rounded-lg border border-status-success/20 bg-status-success/5 p-4 text-sm text-status-success">Selected startup relationship: <span className="font-mono">{projectId}</span></div>}{loading ? <div className="rounded-lg border border-border-inverse bg-surface-inverse p-8 text-center text-text-on-inverse-muted">Loading deal rooms...</div> : deals.length === 0 ? <div className="rounded-lg border border-border-inverse bg-surface-inverse p-10 text-center"><BriefcaseBusiness className="mx-auto mb-3 h-8 w-8 text-text-on-inverse-disabled" /><p className="text-text-on-inverse-secondary">No active Deal Rooms yet.</p><p className="mt-1 text-sm text-text-on-inverse-disabled">Request an introduction from a startup profile, then open a permissioned diligence room.</p></div> : <div className="grid gap-4 md:grid-cols-2">{deals.map((deal) => <Link key={deal.id} to={`/investor/deals/${deal.id}`} className="rounded-lg border border-border-inverse bg-surface-inverse p-5 transition hover:border-status-success/40"><div className="flex items-start justify-between"><div><p className="font-semibold text-white">Project {deal.projectId}</p><p className="mt-1 font-mono text-xs text-text-on-inverse-disabled">{deal.id}</p></div><span className="rounded-full border border-status-info/20 bg-status-info/10 px-2 py-1 text-xs text-status-info">{deal.state}</span></div><div className="mt-5 flex items-center justify-between text-sm"><span className={deal.ndaSigned ? "text-status-success" : "text-status-warning"}><ShieldCheck className="mr-1 inline h-4 w-4" />{deal.ndaSigned ? "NDA signed" : "NDA required"}</span><span className="text-text-on-inverse-muted">{deal.diligence.completed}/{deal.diligence.total} complete <ArrowRight className="ml-1 inline h-4 w-4" /></span></div></Link>)}</div>}</div></div>;
}
