import { useEffect, useState } from "react";
import { AlertTriangle, ArrowUpRight, Brain, CheckCircle2, Clock3, ShieldAlert, type LucideIcon } from "lucide-react";
import { fetchInvestorAlerts, fetchInvestorIntelligenceAdvisory, fetchInvestorIntelligenceOverview, type InvestorAdvisoryResponse, type InvestorAlert, type InvestorIntelligenceOverview } from "@/lib/api/investorIntelligence";
import { Link } from "react-router-dom";

export function InvestorIntelligencePanel() {
  const [data, setData] = useState<InvestorIntelligenceOverview | null>(null); const [alerts, setAlerts] = useState<InvestorAlert[]>([]); const [advisory, setAdvisory] = useState<InvestorAdvisoryResponse | null>(null); const [loading, setLoading] = useState(true); const [advisoryLoading, setAdvisoryLoading] = useState(false); const [lastUpdated, setLastUpdated] = useState<string | null>(null);
  useEffect(() => {
    let alive = true;
    const load = () => Promise.all([fetchInvestorIntelligenceOverview(), fetchInvestorAlerts()]).then(([overview, alertData]) => { if (!alive) return; setData(overview); setAlerts(alertData.alerts); setLastUpdated(new Date().toISOString()); }).catch(() => alive && setData(null)).finally(() => alive && setLoading(false));
    void load();
    const timer = window.setInterval(load, 30_000);
    return () => { alive = false; window.clearInterval(timer); };
  }, []);
  const ask = () => { setAdvisoryLoading(true); fetchInvestorIntelligenceAdvisory().then(setAdvisory).catch(() => setAdvisory(null)).finally(() => setAdvisoryLoading(false)); };
  if (loading) return <div className="mb-6 rounded-lg border border-border-inverse bg-surface-inverse p-6 text-sm text-text-on-inverse-muted">Loading authorized mentorship intelligence...</div>;
  if (!data) return <div className="mb-6 rounded-lg border border-border-inverse bg-surface-inverse p-6 text-sm text-text-on-inverse-muted">Investor intelligence is unavailable for this account.</div>;
  const attention = data.startups.filter((startup) => startup.riskLevel === "high" || startup.riskLevel === "moderate").slice(0, 4);
  const summaryCards: Array<[string, number, LucideIcon]> = [["Authorized startups", data.portfolio.total, ShieldAlert], ["Healthy", data.portfolio.healthy, CheckCircle2], ["On track", data.portfolio.onTrack, ArrowUpRight], ["Needs attention", data.portfolio.highRisk, AlertTriangle]];
  return <section className="mb-6 space-y-4" aria-label="Investor intelligence">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold text-white">Mentorship Intelligence</h2><p className="mt-1 text-sm text-text-on-inverse-muted">Authorized startup-development signals from the existing Mentorship Hub.</p><p className="mt-1 text-xs text-text-on-inverse-disabled">{lastUpdated ? `Updated ${new Date(lastUpdated).toLocaleTimeString()}` : "Connecting to live updates..."}</p></div><button onClick={ask} disabled={advisoryLoading} className="inline-flex items-center gap-2 rounded-lg border border-status-info/30 bg-status-info/10 px-3 py-2 text-sm text-status-info disabled:opacity-60"><Brain className="h-4 w-4" />{advisoryLoading ? "Reviewing..." : "Explain portfolio changes"}</button></div>
    <div className="grid grid-cols-2 gap-3 md:grid-cols-4">{summaryCards.map(([label, value, Icon]) => <div key={label} className="rounded-lg border border-border-inverse bg-surface-inverse p-4"><div className="flex items-center justify-between"><span className="text-xs uppercase tracking-wide text-text-on-inverse-disabled">{label}</span><Icon className="h-4 w-4 text-status-success" /></div><div className="mt-2 font-mono text-2xl font-semibold text-white">{value}</div></div>)}</div>
    <div className="grid gap-4 lg:grid-cols-2"><div className="rounded-lg border border-border-inverse bg-surface-inverse p-5"><h3 className="mb-3 font-medium text-white">What changed</h3>{data.changes.length === 0 ? <p className="text-sm text-text-on-inverse-muted">No meaningful changes since the last intelligence snapshot.</p> : <div className="space-y-3">{data.changes.slice(0, 5).map((change, index) => <div key={`${change.startupId}-${index}`} className="flex gap-3 border-b border-border-inverse pb-3 last:border-0"><Clock3 className="mt-0.5 h-4 w-4 text-status-info" /><div><Link to={`/investor/intelligence/startups/${change.startupId}`} className="text-sm font-medium text-white hover:text-status-success">{change.name}</Link><p className="text-sm text-text-on-inverse-muted">{change.summary}</p></div></div>)}</div>}</div><div className="rounded-lg border border-border-inverse bg-surface-inverse p-5"><h3 className="mb-3 font-medium text-white">Attention required</h3>{attention.length === 0 ? <p className="text-sm text-text-on-inverse-muted">No current risk signals in your authorized scope.</p> : <div className="space-y-3">{attention.map((startup) => <div key={startup.startupId} className="rounded border border-status-warning/20 bg-status-warning/5 p-3"><div className="flex items-center justify-between"><Link to={`/investor/intelligence/startups/${startup.startupId}`} className="font-medium text-white hover:text-status-success">{startup.name}</Link><span className={startup.riskLevel === "high" ? "text-status-error" : "text-status-warning"}>{startup.riskLevel}</span></div><p className="mt-1 text-xs text-text-on-inverse-muted">{startup.milestones.overdue} overdue milestone(s) · {startup.mentorship.completedTasks}/{startup.mentorship.tasks} mentorship tasks complete</p></div>)}</div>}</div></div>
    {advisory && <div className="rounded-lg border border-status-info/20 bg-status-info/5 p-5"><div className="mb-2 flex items-center gap-2 text-sm font-medium text-status-info"><Brain className="h-4 w-4" />AI advisory only</div><p className="text-sm text-text-on-inverse-secondary">{typeof advisory.advisory === "string" ? advisory.advisory : "The AI Router returned an advisory analysis for the authorized evidence."}</p><p className="mt-2 text-xs text-text-on-inverse-disabled">Canonical metrics and access decisions remain backend-controlled.</p></div>}
  </section>;
}
