import { useEffect, useState } from "react";
import { AlertTriangle, ArrowUpRight, Brain, CheckCircle2, Clock3, ShieldAlert } from "lucide-react";
import { fetchInvestorIntelligenceAdvisory, fetchInvestorIntelligenceOverview, type InvestorAdvisoryResponse, type InvestorIntelligenceOverview } from "@/lib/api/investorIntelligence";

export function InvestorIntelligencePanel() {
  const [data, setData] = useState<InvestorIntelligenceOverview | null>(null); const [advisory, setAdvisory] = useState<InvestorAdvisoryResponse | null>(null); const [loading, setLoading] = useState(true); const [advisoryLoading, setAdvisoryLoading] = useState(false);
  useEffect(() => { fetchInvestorIntelligenceOverview().then(setData).catch(() => setData(null)).finally(() => setLoading(false)); }, []);
  const ask = () => { setAdvisoryLoading(true); fetchInvestorIntelligenceAdvisory().then(setAdvisory).catch(() => setAdvisory(null)).finally(() => setAdvisoryLoading(false)); };
  if (loading) return <div className="mb-6 rounded-lg border border-gray-800 bg-[#111111] p-6 text-sm text-gray-400">Loading authorized mentorship intelligence...</div>;
  if (!data) return <div className="mb-6 rounded-lg border border-gray-800 bg-[#111111] p-6 text-sm text-gray-400">Investor intelligence is unavailable for this account.</div>;
  const attention = data.startups.filter((startup) => startup.riskLevel === "high" || startup.riskLevel === "moderate").slice(0, 4);
  return <section className="mb-6 space-y-4" aria-label="Investor intelligence">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold text-white">Mentorship Intelligence</h2><p className="mt-1 text-sm text-gray-400">Authorized startup-development signals from the existing Mentorship Hub.</p></div><button onClick={ask} disabled={advisoryLoading} className="inline-flex items-center gap-2 rounded-lg border border-blue-500/30 bg-blue-500/10 px-3 py-2 text-sm text-blue-300 disabled:opacity-60"><Brain className="h-4 w-4" />{advisoryLoading ? "Reviewing..." : "Explain portfolio changes"}</button></div>
    <div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[["Authorized startups", data.portfolio.total, ShieldAlert], ["Healthy", data.portfolio.healthy, CheckCircle2], ["On track", data.portfolio.onTrack, ArrowUpRight], ["Needs attention", data.portfolio.highRisk, AlertTriangle]].map(([label, value, Icon]) => <div key={String(label)} className="rounded-lg border border-gray-800 bg-[#111111] p-4"><div className="flex items-center justify-between"><span className="text-xs uppercase tracking-wide text-gray-500">{String(label)}</span><Icon className="h-4 w-4 text-emerald-400" /></div><div className="mt-2 font-mono text-2xl font-semibold text-white">{String(value)}</div></div>)}</div>
    <div className="grid gap-4 lg:grid-cols-2"><div className="rounded-lg border border-gray-800 bg-[#111111] p-5"><h3 className="mb-3 font-medium text-white">What changed</h3>{data.changes.length === 0 ? <p className="text-sm text-gray-400">No meaningful changes since the last intelligence snapshot.</p> : <div className="space-y-3">{data.changes.slice(0, 5).map((change, index) => <div key={`${change.startupId}-${index}`} className="flex gap-3 border-b border-gray-800 pb-3 last:border-0"><Clock3 className="mt-0.5 h-4 w-4 text-blue-400" /><div><p className="text-sm font-medium text-white">{change.name}</p><p className="text-sm text-gray-400">{change.summary}</p></div></div>)}</div>}</div><div className="rounded-lg border border-gray-800 bg-[#111111] p-5"><h3 className="mb-3 font-medium text-white">Attention required</h3>{attention.length === 0 ? <p className="text-sm text-gray-400">No current risk signals in your authorized scope.</p> : <div className="space-y-3">{attention.map((startup) => <div key={startup.startupId} className="rounded border border-amber-500/20 bg-amber-500/5 p-3"><div className="flex items-center justify-between"><span className="font-medium text-white">{startup.name}</span><span className={startup.riskLevel === "high" ? "text-red-300" : "text-amber-300"}>{startup.riskLevel}</span></div><p className="mt-1 text-xs text-gray-400">{startup.milestones.overdue} overdue milestone(s) · {startup.mentorship.completedTasks}/{startup.mentorship.tasks} mentorship tasks complete</p></div>)}</div>}</div></div>
    {advisory && <div className="rounded-lg border border-blue-500/20 bg-blue-500/5 p-5"><div className="mb-2 flex items-center gap-2 text-sm font-medium text-blue-200"><Brain className="h-4 w-4" />AI advisory only</div><p className="text-sm text-gray-300">{typeof advisory.advisory === "string" ? advisory.advisory : "The AI Router returned an advisory analysis for the authorized evidence."}</p><p className="mt-2 text-xs text-gray-500">Canonical metrics and access decisions remain backend-controlled.</p></div>}
  </section>;
}
