import { useEffect, useMemo, useState } from "react";
import { Plus, RefreshCw, Save } from "lucide-react";
import { toast } from "sonner";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { createOrganizationSectionRecord, fetchOrganizationSection, updateOrganizationSectionRecord, type OrganizationLiveRecord, type OrganizationLiveSection } from "@/lib/api/organization";

export type LiveField = { key: string; label: string; placeholder?: string; multiline?: boolean; type?: string };
export function LiveCollectionPage({ section, title, description, itemLabel, fields }: { section: OrganizationLiveSection; title: string; description: string; itemLabel: string; fields: LiveField[] }) {
  const [records, setRecords] = useState<OrganizationLiveRecord[]>([]); const [loading, setLoading] = useState(true); const [creating, setCreating] = useState(false); const [draft, setDraft] = useState<Record<string, string>>({});
  const load = () => { setLoading(true); fetchOrganizationSection(section).then(setRecords).catch(() => toast.error(`Unable to load ${title.toLowerCase()}.`)).finally(() => setLoading(false)); };
  useEffect(load, [section]);
  const summaryFields = useMemo(() => fields.slice(0, 4), [fields]);
  const create = async () => { if (!String(draft[fields[0].key] || "").trim()) return toast.error(`${fields[0].label} is required.`); setCreating(true); try { const record = await createOrganizationSectionRecord(section, draft); setRecords((current) => [record, ...current]); setDraft({}); toast.success(`${itemLabel} created.`); } catch { toast.error(`Unable to create ${itemLabel.toLowerCase()}.`); } finally { setCreating(false); } };
  const changeStatus = async (record: OrganizationLiveRecord, status: string) => { try { const updated = await updateOrganizationSectionRecord(section, record.id, { status }); setRecords((current) => current.map((item) => item.id === record.id ? updated : item)); toast.success("Status updated."); } catch { toast.error("Unable to update status."); } };
  return <div className="mx-auto max-w-[1500px] space-y-6 p-6 lg:p-8">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-semibold">{title}</h1><p className="mt-2 text-muted-foreground">{description}</p></div><button onClick={load} className="inline-flex h-10 w-10 items-center justify-center rounded-md border" title="Refresh"><RefreshCw className="h-4 w-4" /></button></div>
    <Card><CardHeader><CardTitle className="text-lg">Add {itemLabel}</CardTitle></CardHeader><CardContent><div className="grid gap-4 md:grid-cols-2">{fields.map((field) => <div key={field.key} className={field.multiline ? "md:col-span-2" : ""}><Label htmlFor={`${section}-${field.key}`}>{field.label}</Label>{field.multiline ? <Textarea id={`${section}-${field.key}`} value={draft[field.key] || ""} onChange={(e) => setDraft({ ...draft, [field.key]: e.target.value })} placeholder={field.placeholder} /> : <Input id={`${section}-${field.key}`} type={field.type || "text"} value={draft[field.key] || ""} onChange={(e) => setDraft({ ...draft, [field.key]: e.target.value })} placeholder={field.placeholder} />}</div>)}</div><button disabled={creating} onClick={create} className="mt-4 inline-flex items-center gap-2 rounded-md bg-primary px-4 py-2 text-primary-foreground disabled:opacity-50"><Plus className="h-4 w-4" />{creating ? "Saving..." : `Add ${itemLabel}`}</button></CardContent></Card>
    {loading ? <div className="py-12 text-center text-muted-foreground">Loading live records...</div> : records.length === 0 ? <Card><CardContent className="py-12 text-center text-muted-foreground">No {title.toLowerCase()} records yet.</CardContent></Card> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{records.map((record) => <Card key={record.id}><CardHeader><CardTitle className="text-base">{String(record.title || record.name || record[fields[0].key] || itemLabel)}</CardTitle></CardHeader><CardContent className="space-y-3">{summaryFields.map((field) => record[field.key] ? <div key={field.key}><p className="text-xs font-medium uppercase text-muted-foreground">{field.label}</p><p className="break-words text-sm">{String(record[field.key])}</p></div> : null)}<div className="flex gap-2"><button onClick={() => changeStatus(record, "active")} className="inline-flex items-center gap-1 rounded-md border px-3 py-1.5 text-sm"><Save className="h-3.5 w-3.5" />Active</button><button onClick={() => changeStatus(record, "archived")} className="rounded-md border px-3 py-1.5 text-sm">Archive</button></div></CardContent></Card>)}</div>}
  </div>;
}
