import { useEffect, useState } from "react";
import type { ReactNode } from "react";
import { BarChart3, BriefcaseBusiness, Boxes, RefreshCw } from "lucide-react";
import { fetchOrganizationAlumni, fetchOrganizationCohortBenchmarks, fetchOrganizationResourceAllocation, type OrganizationAlumni, type OrganizationBenchmark, type OrganizationAllocation } from "@/lib/api/organizationIntelligence";

function Empty({ children }: { children: string }) { return <div className="rounded-lg border border-dashed border-border-default bg-background-primary px-5 py-8 text-center text-sm text-text-muted">{children}</div>; }
function Panel({ title, icon: Icon, children }: { title: string; icon: typeof Boxes; children: ReactNode }) { return <section className="rounded-lg border border-border-default bg-surface-primary p-6 shadow-sm"><h2 className="mb-4 flex items-center gap-2 text-lg font-bold text-text-primary"><Icon className="h-5 w-5 text-brand-accent" />{title}</h2>{children}</section>; }

export function ResourceAllocation() { const [rows, setRows] = useState<OrganizationAllocation[]>([]); const [loading, setLoading] = useState(true); const load = () => { setLoading(true); fetchOrganizationResourceAllocation().then((data) => setRows(data.allocation)).catch(() => setRows([])).finally(() => setLoading(false)); }; useEffect(load, []); return <Panel title="Resource allocation" icon={Boxes}>{loading ? <p className="text-sm text-text-muted">Loading allocation signals...</p> : rows.length === 0 ? <Empty>No resource or execution allocation data is available.</Empty> : <div className="space-y-3">{rows.slice(0, 10).map((row) => <div key={row.projectId} className="rounded border border-border-subtle p-3"><div className="flex items-center justify-between gap-3"><span className="font-medium text-text-primary">{row.title}</span><span className="text-sm text-brand-accent">{row.utilization === null ? "—" : `${row.utilization}% utilized`}</span></div><p className="mt-1 text-xs text-text-muted">{row.resources} resources · {row.completedTasks}/{row.tasks} tasks completed · execution {row.execution ?? "—"}</p></div>)}</div>}</Panel>; }
export function AlumniOutcomes() { const [rows, setRows] = useState<OrganizationAlumni[]>([]); const [loading, setLoading] = useState(true); useEffect(() => { fetchOrganizationAlumni().then((data) => setRows(data.outcomes)).catch(() => setRows([])).finally(() => setLoading(false)); }, []); return <Panel title="Alumni outcomes" icon={BriefcaseBusiness}>{loading ? <p className="text-sm text-text-muted">Loading alumni outcomes...</p> : rows.length === 0 ? <Empty>No completed or graduated startups have outcome records yet.</Empty> : <div className="grid gap-3 sm:grid-cols-2">{rows.map((row) => <div key={row.id} className="rounded border border-border-subtle p-3"><p className="font-medium text-text-primary">{row.title}</p><p className="mt-1 text-xs text-text-muted">{row.status} · funding {row.funding ?? "—"} · jobs {row.jobs ?? "—"} · revenue {row.revenue ?? "—"}</p></div>)}</div>}</Panel>; }
export function CohortBenchmarks() { const [rows, setRows] = useState<OrganizationBenchmark[]>([]); const [loading, setLoading] = useState(true); useEffect(() => { fetchOrganizationCohortBenchmarks().then(setRows).catch(() => setRows([])).finally(() => setLoading(false)); }, []); return <Panel title="Cross-cohort benchmarks" icon={BarChart3}>{loading ? <p className="text-sm text-text-muted">Loading cohort benchmarks...</p> : rows.length === 0 ? <Empty>No cohort comparison data is available yet.</Empty> : <div className="space-y-3">{rows.map((row) => <div key={row.cohortId} className="grid grid-cols-2 gap-3 rounded border border-border-subtle p-3 sm:grid-cols-5"><div className="col-span-2 font-medium text-text-primary sm:col-span-1">{row.name}</div><div><p className="text-xs text-text-muted">Startups</p><p className="font-semibold text-text-primary">{row.startups}</p></div><div><p className="text-xs text-text-muted">Health</p><p className="font-semibold text-text-primary">{row.avgHealth ?? "—"}</p></div><div><p className="text-xs text-text-muted">Progress</p><p className="font-semibold text-text-primary">{row.avgProgress ?? "—"}</p></div><div><p className="text-xs text-text-muted">Engagement</p><p className="font-semibold text-text-primary">{row.engagement ?? "—"}</p></div></div>)}</div>}</Panel>; }
