import { useEffect, useState } from "react";
import { useLocation, useParams } from "react-router-dom";
import { Copy, Plus, Send, Share2 } from "lucide-react";
import { toast } from "sonner";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Progress } from "@/components/ui/progress";
import { createMentorshipInvite, createMentorshipMessage, createMentorshipResource, createMentorshipTask, getMentorshipRoom, getMentorshipShare, publishMentorshipToFeed, broadcastMentorshipOpportunity, type MentorshipRoom, type MentorshipTask, type SharePayload } from "@/lib/api/mentorship";
import { ACCENT_SOLID, ACCENT_SOFT, HERO_GRADIENT, NEUTRAL_BTN, statusBadge } from "./theme";

export function Room() {
  const { roomId } = useParams();
  const location = useLocation();
  const base = location.pathname.startsWith("/founder/") ? "/founder/mentorship" : "/investor/mentorship";
  const [room, setRoom] = useState<MentorshipRoom | null>(null);
  const [mentees, setMentees] = useState<Array<Record<string, any>>>([]);
  const [tasks, setTasks] = useState<MentorshipTask[]>([]);
  const [messages, setMessages] = useState<Array<Record<string, any>>>([]);
  const [resources, setResources] = useState<Array<Record<string, any>>>([]);
  const [share, setShare] = useState<SharePayload | null>(null);
  const [message, setMessage] = useState(""); const [resourceUrl, setResourceUrl] = useState(""); const [taskTitle, setTaskTitle] = useState(""); const [taskDescription, setTaskDescription] = useState("");
  const load = () => { if (!roomId) return; getMentorshipRoom(roomId).then((data) => { setRoom(data.room); setMentees(data.mentees); setTasks(data.tasks); setMessages(data.messages); setResources(data.resources); }).catch(() => toast.error("Unable to load mentorship room.")); };
  useEffect(load, [roomId]);
  if (!room) return <div className="text-muted-foreground">Loading mentorship room...</div>;
  const invite = async () => { try { const result = await createMentorshipInvite(room.id); await navigator.clipboard?.writeText(result.invitation.url); toast.success("Secure invite link copied."); } catch { toast.error("Unable to create invite."); } };
  const feed = async () => { try { await publishMentorshipToFeed(room.id); toast.success("Published to TechIT Feed."); } catch { toast.error("Unable to publish to Feed."); } };
  const opportunity = async () => { try { await broadcastMentorshipOpportunity(room.id); toast.success("Broadcast to Opportunities."); } catch { toast.error("Unable to broadcast opportunity."); } };
  const send = async () => { if (!message.trim()) return; try { const result = await createMentorshipMessage(room.id, { content: message }); setMessages((items) => [...items, result.message as any]); setMessage(""); } catch { toast.error("Unable to send message."); } };
  const addResource = async () => { if (!resourceUrl.trim()) return; try { const result = await createMentorshipResource(room.id, { title: resourceUrl, url: resourceUrl }); setResources((items) => [...items, result.resource as any]); setResourceUrl(""); toast.success("Resource added."); } catch { toast.error("Enter a valid http(s) URL."); } };
  const addTask = async () => { if (!taskTitle.trim()) return; try { const result = await createMentorshipTask(room.id, { title: taskTitle, description: taskDescription }); setTasks((items) => [...items, result.task]); setTaskTitle(""); setTaskDescription(""); toast.success("Task created."); } catch { toast.error("Unable to create task."); } };
  return <div className="space-y-6">
    <div className={`rounded-lg p-6 ${HERO_GRADIENT}`}><h1 className="mb-2 text-3xl">{room.name}</h1><p className="mb-4 text-white/80">{room.description}</p><div className="flex gap-4"><div className="rounded-lg bg-surface-primary/20 px-4 py-2"><div className="text-sm text-white/80">Payment model</div><div className="font-semibold">{room.paymentModel}</div></div><div className="rounded-lg bg-surface-primary/20 px-4 py-2"><div className="text-sm text-white/80">Active mentees</div><div className="font-semibold">{mentees.length} / {room.capacity}</div></div></div></div>
    <Card><CardContent className="flex flex-wrap items-center gap-2 p-4"><Share2 className="h-4 w-4" /><span className="mr-auto font-medium">Share this mentorship room</span><button onClick={invite} className={`rounded-lg px-3 py-2 text-sm ${ACCENT_SOLID}`}><Copy className="mr-1 inline h-4 w-4" />Invite link</button><button onClick={feed} className={`rounded-lg px-3 py-2 text-sm ${NEUTRAL_BTN}`}>TechIT Feed</button><button onClick={opportunity} className={`rounded-lg px-3 py-2 text-sm ${NEUTRAL_BTN}`}>Opportunities</button><button onClick={async () => { try { setShare(await getMentorshipShare(room.id)); } catch { toast.error("Unable to load social links."); } }} className={`rounded-lg px-3 py-2 text-sm ${NEUTRAL_BTN}`}>Social links</button>{share && <div className="basis-full flex flex-wrap gap-2 border-t pt-3">{Object.entries(share.social).map(([name, url]) => <a key={name} href={url} target="_blank" rel="noreferrer" className="rounded border px-2 py-1 text-sm capitalize">{name}</a>)}</div>}</CardContent></Card>
    <div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>Mentees</CardTitle></CardHeader><CardContent className="space-y-3">{mentees.length === 0 && <p className="text-sm text-muted-foreground">No active mentees yet.</p>}{mentees.map((mentee) => <div key={String(mentee.id)} className="rounded border p-3"><div className="font-medium">{String(mentee.name || mentee.userId || "Mentee")}</div><div className="text-sm text-muted-foreground">{String(mentee.email || mentee.userId || "")}</div><Progress value={Number(mentee.progress || 0)} className="mt-2" /></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Tasks</CardTitle></CardHeader><CardContent className="space-y-3"><Input value={taskTitle} onChange={(e) => setTaskTitle(e.target.value)} placeholder="Task title" /><Textarea value={taskDescription} onChange={(e) => setTaskDescription(e.target.value)} placeholder="Task description" /><button onClick={addTask} className={`rounded-lg px-3 py-2 text-sm ${ACCENT_SOLID}`}><Plus className="mr-1 inline h-4 w-4" />Create task</button>{tasks.map((task) => <div key={task.id} className="rounded border p-3"><div className="flex items-center gap-2"><span className="font-medium">{task.title}</span><Badge className={statusBadge(task.status)}>{task.status}</Badge></div><p className="text-sm text-muted-foreground">{task.description}</p></div>)}</CardContent></Card></div>
    <Card><CardHeader><CardTitle>Room communication</CardTitle></CardHeader><CardContent className="space-y-3"><div className="max-h-72 space-y-2 overflow-y-auto rounded bg-muted/50 p-3">{messages.length === 0 && <p className="text-sm text-muted-foreground">No messages yet.</p>}{messages.map((item) => <div key={String(item.id)} className="rounded bg-card p-2"><div className="text-xs text-muted-foreground">{String(item.senderId)}</div><div className="text-sm">{String(item.content)}</div></div>)}</div><div className="flex gap-2"><Input value={message} onChange={(e) => setMessage(e.target.value)} placeholder="Type a message" /><button onClick={send} className={`rounded-lg px-3 py-2 ${ACCENT_SOLID}`}><Send className="h-4 w-4" /></button></div></CardContent></Card>
    <Card><CardHeader><CardTitle>Shared resources</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex gap-2"><Input value={resourceUrl} onChange={(e) => setResourceUrl(e.target.value)} placeholder="https://resource.example" /><button onClick={addResource} className={`rounded-lg px-3 py-2 ${NEUTRAL_BTN}`}>Add</button></div>{resources.length === 0 && <p className="text-sm text-muted-foreground">No resources shared yet.</p>}{resources.map((resource) => <a key={String(resource.id)} href={String(resource.url)} target="_blank" rel="noreferrer" className="block rounded border p-3 text-sm hover:bg-accent">{String(resource.title)}<span className="block text-xs text-muted-foreground">{String(resource.url)}</span></a>)}</CardContent></Card>
  </div>;
}
