/**
 * Authoritative TechIT visual contract.
 *
 * Raw reusable colors belong here. Runtime CSS is generated from this object;
 * application components consume semantic CSS/Tailwind tokens only.
 */
export const techITTheme = {
  brand: {
    primary: '#2196f3',
    primaryHover: '#1976d2',
    secondary: '#0a1929',
    accent: '#4f6ef7',
    premium: '#ffd700',
  },
  inverse: {
    background: '#0a0a0a',
    backgroundSecondary: '#0d0d0d',
    surface: '#111111',
    surfaceMuted: '#1f2937',
    text: '#f3f4f6',
    textSecondary: '#d1d5db',
    textMuted: '#9ca3af',
    textDisabled: '#6b7280',
    border: '#1f2937',
    borderStrong: '#374151',
  },
  status: {
    success: '#10b981',
    warning: '#f59e0b',
    error: '#ef4444',
    info: '#2196f3',
    pending: '#a855f7',
    active: '#10b981',
    inactive: '#64748b',
    disabled: '#94a3b8',
    successSoft: 'rgba(16, 185, 129, 0.12)',
    warningSoft: 'rgba(245, 158, 11, 0.12)',
    errorSoft: 'rgba(239, 68, 68, 0.12)',
    infoSoft: 'rgba(33, 150, 243, 0.12)',
    pendingSoft: 'rgba(168, 85, 247, 0.12)',
  },
  role: {
    explorer: { primary: '#4f6ef7', hover: '#3b5de7', soft: '#eef2ff', muted: '#e0e7ff', strong: '#3730a3' },
    founder: { primary: '#7c3aed', hover: '#6d28d9', soft: '#f5f3ff', muted: '#ede9fe', strong: '#5b21b6' },
    collaborator: { primary: '#f59e0b', hover: '#d97706', soft: '#fffbeb', muted: '#fef3c7', strong: '#92400e' },
    investor: { primary: '#10b981', hover: '#059669', soft: '#ecfdf5', muted: '#d1fae5', strong: '#065f46' },
    organization: { primary: '#4f46e5', hover: '#4338ca', soft: '#eef2ff', muted: '#e0e7ff', strong: '#312e81' },
  },
  feature: {
    incubation: '#7c3aed',
    incubationHover: '#6d28d9',
    incubationSoft: '#f5f3ff',
    incubationMuted: '#ede9fe',
    code: '#06b6d4',
    codeStrong: '#0e7490',
    callOverlay: '#1a2942',
  },
  chart: {
    one: '#10b981',
    two: '#3b82f6',
    three: '#8b5cf6',
    four: '#f59e0b',
    five: '#ec4899',
    six: '#06b6d4',
  },
  integration: {
    linkedin: '#0a66c2',
    slack: '#0a66c2',
    jira: '#ff6b6b',
  },
  marketing: {
    founderCardGradient: 'linear-gradient(135deg, #7c3aed, #a855f7)',
    founderCardAccent: '#a855f7',
    collaboratorCardGradient: 'linear-gradient(135deg, #0ea5e9, #06b6d4)',
    collaboratorCardAccent: '#06b6d4',
    investorCardGradient: 'linear-gradient(135deg, #10b981, #06b6d4)',
    investorCardAccent: '#10b981',
    organizationCardGradient: 'linear-gradient(135deg, #f43f5e, #ec4899)',
    organizationCardAccent: '#f43f5e',
    paidCollaborationSoft: 'rgba(124, 58, 237, 0.18)',
    paidCollaboration: '#7c3aed',
    freeCollaborationSoft: 'rgba(234, 179, 8, 0.14)',
    freeCollaboration: '#eab308',
    hiringSoft: 'rgba(236, 72, 153, 0.14)',
    hiring: '#ec4899',
  },
  gradient: {
    brand: 'linear-gradient(135deg, #2196f3, #4f6ef7)',
    brandSubtle: 'linear-gradient(135deg, rgba(33, 150, 243, 0.12), rgba(79, 110, 247, 0.08))',
  },
  shadow: {
    elevated: '0 8px 24px rgba(15, 23, 42, 0.12)',
    focus: '0 0 0 3px rgba(33, 150, 243, 0.24)',
  },
  editor: {
    background: '#1e1e1e',
  },
  modes: {
    light: {
      background: {
        primary: '#f6f8fb',
        secondary: '#ffffff',
        tertiary: '#f0f3f7',
      },
      surface: {
        primary: '#ffffff',
        secondary: '#f0f3f7',
        elevated: '#ffffff',
        overlay: '#ffffff',
      },
      text: {
        primary: '#172033',
        secondary: '#475569',
        muted: '#64748b',
        disabled: '#94a3b8',
        inverse: '#ffffff',
      },
      border: {
        default: '#e4e8ef',
        subtle: '#eef1f5',
        strong: '#cbd3df',
      },
      action: {
        primary: '#2196f3',
        primaryHover: '#1976d2',
        secondary: '#0a1929',
        danger: '#ef4444',
      },
      landing: {
        backgroundPrimary: '#ffffff',
        backgroundSecondary: '#f9f9ff',
        backgroundTertiary: '#f0f0fa',
        textPrimary: '#050515',
        textSecondary: '#666680',
        textTertiary: '#999999',
        border: '#e5e5e8',
        accentPrimary: '#7c3aed',
        accentSecondary: '#0891b2',
        accentSuccess: '#059669',
      },
    },
    dark: {
      background: {
        primary: '#0a0a0f',
        secondary: '#111118',
        tertiary: '#1a1a25',
      },
      surface: {
        primary: '#111118',
        secondary: '#1a1a25',
        elevated: '#22222e',
        overlay: '#22222e',
      },
      text: {
        primary: '#f0f0f5',
        secondary: '#c4c4d4',
        muted: '#9090a8',
        disabled: '#5c5c78',
        inverse: '#0a0a0f',
      },
      border: {
        default: 'rgba(255, 255, 255, 0.08)',
        subtle: 'rgba(255, 255, 255, 0.04)',
        strong: 'rgba(255, 255, 255, 0.18)',
      },
      action: {
        primary: '#4f6ef7',
        primaryHover: '#6d86ff',
        secondary: '#2196f3',
        danger: '#ef4444',
      },
      status: {
        info: '#60a5fa',
      },
      gradient: {
        brand: 'linear-gradient(135deg, #4f6ef7, #2196f3)',
        brandSubtle: 'linear-gradient(135deg, rgba(79, 110, 247, 0.2), rgba(33, 150, 243, 0.12))',
      },
      shadow: {
        elevated: '0 8px 24px rgba(0, 0, 0, 0.35)',
        focus: '0 0 0 3px rgba(79, 110, 247, 0.3)',
      },
      landing: {
        backgroundPrimary: '#05050f',
        backgroundSecondary: '#0a0a1f',
        backgroundTertiary: '#151530',
        textPrimary: '#ffffff',
        textSecondary: '#b0b0d0',
        textTertiary: '#808090',
        border: '#2a2a4a',
        accentPrimary: '#7c3aed',
        accentSecondary: '#06b6d4',
        accentSuccess: '#10b981',
      },
    },
  },
} as const

export const themeCssVariables = {
  shared: {
    'brand-primary': techITTheme.brand.primary,
    'brand-primary-hover': techITTheme.brand.primaryHover,
    'brand-secondary': techITTheme.brand.secondary,
    'brand-accent': techITTheme.brand.accent,
    'brand-premium': techITTheme.brand.premium,
    'background-inverse': techITTheme.inverse.background,
    'background-inverse-secondary': techITTheme.inverse.backgroundSecondary,
    'surface-inverse': techITTheme.inverse.surface,
    'surface-inverse-muted': techITTheme.inverse.surfaceMuted,
    'text-on-inverse': techITTheme.inverse.text,
    'text-on-inverse-secondary': techITTheme.inverse.textSecondary,
    'text-on-inverse-muted': techITTheme.inverse.textMuted,
    'text-on-inverse-disabled': techITTheme.inverse.textDisabled,
    'border-inverse': techITTheme.inverse.border,
    'border-inverse-strong': techITTheme.inverse.borderStrong,
    'status-success': techITTheme.status.success,
    'status-warning': techITTheme.status.warning,
    'status-error': techITTheme.status.error,
    'status-info': techITTheme.status.info,
    'status-pending': techITTheme.status.pending,
    'status-active': techITTheme.status.active,
    'status-inactive': techITTheme.status.inactive,
    'status-disabled': techITTheme.status.disabled,
    'status-success-soft': techITTheme.status.successSoft,
    'status-warning-soft': techITTheme.status.warningSoft,
    'status-error-soft': techITTheme.status.errorSoft,
    'status-info-soft': techITTheme.status.infoSoft,
    'status-pending-soft': techITTheme.status.pendingSoft,
    'role-explorer': techITTheme.role.explorer.primary,
    'role-explorer-hover': techITTheme.role.explorer.hover,
    'role-explorer-soft': techITTheme.role.explorer.soft,
    'role-explorer-muted': techITTheme.role.explorer.muted,
    'role-explorer-strong': techITTheme.role.explorer.strong,
    'role-founder': techITTheme.role.founder.primary,
    'role-founder-hover': techITTheme.role.founder.hover,
    'role-founder-soft': techITTheme.role.founder.soft,
    'role-founder-muted': techITTheme.role.founder.muted,
    'role-founder-strong': techITTheme.role.founder.strong,
    'role-collaborator': techITTheme.role.collaborator.primary,
    'role-collaborator-hover': techITTheme.role.collaborator.hover,
    'role-collaborator-soft': techITTheme.role.collaborator.soft,
    'role-collaborator-muted': techITTheme.role.collaborator.muted,
    'role-collaborator-strong': techITTheme.role.collaborator.strong,
    'role-investor': techITTheme.role.investor.primary,
    'role-investor-hover': techITTheme.role.investor.hover,
    'role-investor-soft': techITTheme.role.investor.soft,
    'role-investor-muted': techITTheme.role.investor.muted,
    'role-investor-strong': techITTheme.role.investor.strong,
    'role-organization': techITTheme.role.organization.primary,
    'role-organization-hover': techITTheme.role.organization.hover,
    'role-organization-soft': techITTheme.role.organization.soft,
    'role-organization-muted': techITTheme.role.organization.muted,
    'role-organization-strong': techITTheme.role.organization.strong,
    'feature-incubation': techITTheme.feature.incubation,
    'feature-incubation-hover': techITTheme.feature.incubationHover,
    'feature-incubation-soft': techITTheme.feature.incubationSoft,
    'feature-incubation-muted': techITTheme.feature.incubationMuted,
    'feature-code': techITTheme.feature.code,
    'feature-code-strong': techITTheme.feature.codeStrong,
    'feature-call-overlay': techITTheme.feature.callOverlay,
    'chart-1': techITTheme.chart.one,
    'chart-2': techITTheme.chart.two,
    'chart-3': techITTheme.chart.three,
    'chart-4': techITTheme.chart.four,
    'chart-5': techITTheme.chart.five,
    'chart-6': techITTheme.chart.six,
    'integration-linkedin': techITTheme.integration.linkedin,
    'integration-slack': techITTheme.integration.slack,
    'integration-jira': techITTheme.integration.jira,
    'marketing-founder-card-gradient': techITTheme.marketing.founderCardGradient,
    'marketing-founder-card-accent': techITTheme.marketing.founderCardAccent,
    'marketing-collaborator-card-gradient': techITTheme.marketing.collaboratorCardGradient,
    'marketing-collaborator-card-accent': techITTheme.marketing.collaboratorCardAccent,
    'marketing-investor-card-gradient': techITTheme.marketing.investorCardGradient,
    'marketing-investor-card-accent': techITTheme.marketing.investorCardAccent,
    'marketing-organization-card-gradient': techITTheme.marketing.organizationCardGradient,
    'marketing-organization-card-accent': techITTheme.marketing.organizationCardAccent,
    'marketing-paid-collaboration-soft': techITTheme.marketing.paidCollaborationSoft,
    'marketing-paid-collaboration': techITTheme.marketing.paidCollaboration,
    'marketing-free-collaboration-soft': techITTheme.marketing.freeCollaborationSoft,
    'marketing-free-collaboration': techITTheme.marketing.freeCollaboration,
    'marketing-hiring-soft': techITTheme.marketing.hiringSoft,
    'marketing-hiring': techITTheme.marketing.hiring,
    'gradient-brand': techITTheme.gradient.brand,
    'gradient-brand-subtle': techITTheme.gradient.brandSubtle,
    'shadow-elevated': techITTheme.shadow.elevated,
    'shadow-focus': techITTheme.shadow.focus,
    'editor-background': techITTheme.editor.background,
  },
  light: techITTheme.modes.light,
  dark: techITTheme.modes.dark,
} as const

export type TechITRole = keyof typeof techITTheme.role
export type TechITTheme = typeof techITTheme
