import type { FileSystemTree, WebContainer, WebContainerProcess } from '@webcontainer/api';
let instance: WebContainer | null = null;
let booting: Promise<WebContainer> | null = null;
let activeProcess: WebContainerProcess | null = null;
export async function bootWebContainer(timeoutMs = 30_000): Promise<WebContainer> { if (instance) return instance; if (!booting) booting = import('@webcontainer/api').then(({ WebContainer }) => WebContainer.boot({ coep: 'credentialless' })); let timeout: ReturnType<typeof setTimeout> | undefined; let timedOut = false; try { instance = await Promise.race([booting, new Promise<never>((_resolve, reject) => { timeout = setTimeout(() => { timedOut = true; reject(new Error(`WebContainer boot timed out after ${Math.round(timeoutMs / 1000)} seconds.`)); }, timeoutMs); })]); return instance; } catch (error) { if (!timedOut) booting = null; throw error; } finally { if (timeout) clearTimeout(timeout); if (instance) booting = null; } }
export function treeFromFiles(files: Array<{ path: string; content: string }>): FileSystemTree { const root: FileSystemTree = {}; for (const file of files) { const parts = file.path.split('/').filter(Boolean); let level = root; parts.forEach((part, index) => { if (index === parts.length - 1) level[part] = { file: { contents: file.content } }; else { const existing = level[part]; if (!existing || !('directory' in existing)) level[part] = { directory: {} }; level = (level[part] as { directory: FileSystemTree }).directory; } }); } return root; }
export async function runWebCommand(files: Array<{ path: string; content: string }>, command: string, onOutput: (chunk: string) => void, onServerReady?: (url: string) => void, timeoutMs = 120_000) { const container = await bootWebContainer(); await container.mount(treeFromFiles(files)); if (onServerReady) container.on('server-ready', (_port, url) => onServerReady(url)); const [program, ...args] = command.trim().split(/\s+/); if (!program) throw new Error('No adapter command is configured.'); const process = await container.spawn(program, args); activeProcess = process; void process.output.pipeTo(new WritableStream({ write(data) { onOutput(data); } })); if (onServerReady) return { exitCode: null, process }; let timeout: ReturnType<typeof setTimeout> | undefined; try { const exitCode = await Promise.race([process.exit, new Promise<never>((_resolve, reject) => { timeout = setTimeout(() => { process.kill(); reject(new Error(`Command timed out after ${Math.round(timeoutMs / 1000)} seconds.`)); }, timeoutMs); })]); return { exitCode, process }; } finally { if (timeout) clearTimeout(timeout); if (activeProcess === process) activeProcess = null; } }
export function stopWebCommand() { activeProcess?.kill(); activeProcess = null; }
export async function restartWebContainer() { stopWebCommand(); instance?.teardown(); instance = null; return bootWebContainer(); }
